spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/animes
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true